FROM docker-registry.na.intgdc.com/gdc_el7:R24.3
RUN yum install -y gcc python-devel python-pip libffi-devel libjpeg-turbo-devel openssl-devel
RUN pip install tox
WORKDIR /zuul
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
